name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download source
        uses: actions/checkout@v4

      - name: Build
        shell: cmd
        run: |
          msbuild "*.sln" /m /p:Configuration=Release /p:Platform=x64

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Windows-EXE
          path: |
            **/Release/*.exe
            **/x64/Release/*.exe
